### ISSUE TITLE
Theme toggle is difficult to use; improve UX

### ISSUE THREAD

**Issue by plainspace** [plainspace/join-dev-design#1]
As a user I'd like to be able to mouse over the toggle and not have to move my mouse position to use the toggle.

**Comment by plainspace** [comment]
Consider using MS styles: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/toggles

**Comment by dvdsgl** [comment]
I'm not specifically interested in using Windows/UWP style on the site 😄
